/*
 * This source file was generated by the Gradle 'init' task
 */
package sortingengine;

import java.nio.file.Path;

import sortingengine.conf.LaunchConfig;

public class App
{
    public static void main(String[] args) throws Exception
    {
        final String launchConfigPath = args.length > 0 ? args[0] : LaunchConfig.DEFAULT_CONFIG_PATH;
        LaunchConfig.load(Path.of(launchConfigPath));

        Server server = new Server(LaunchConfig.getInstance().port);
        server.run();
    }
}
